# Numpy (Numerical Python)
* It's an linear algebra library
* It gives us n-d arrays (1-D,2-D..)
* Can contain only homogenous elements (i.e. elements of same type)
## Advantage:
    * Numpy arrays takes less amount of space as compared to list
    * Numpy arrays are much faster
    * Numpy array is easier to use than list
    * Functionality: Numpy arrays has more functionality over list

In [2]:
import numpy as np

In [3]:
dt = np.dtype('>i4') 
# (i4 represents an integer of size 4 byte “>” represents big-endian byte ordering and “<” represents little-endian encoding)
print(dt.name)

int32


In [2]:
li_arr = [
    i
    for i in range(100)
]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
# size of 1 element in numpy array
print(np_arr.itemsize)

# size of 100 elements in numpy array
print(np_arr.itemsize*np_arr.size)

4
400


In [6]:
import sys

# size of one element in a list
print(sys.getsizeof(li_arr[0]))

# size of 100 element in a list
print(sys.getsizeof(li_arr[0])*len(li_arr))

24
2400


# Create NumPy Arrays

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = np.array(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3 4]


In [4]:
a = [1,2,4.6,'a','b',8.9,0]
b = np.array(a)
print(b)
print(type(b))

['1' '2' '4.6' 'a' 'b' '8.9' '0']
<class 'numpy.ndarray'>


In [6]:
a = [1,2,4.6,8.9,0]
b = np.array(a, dtype = int)
print(b)
print(type(b))

[1 2 4 8 0]
<class 'numpy.ndarray'>


In [9]:
a = [1,2,3,4]
b = np.array(a*3)
print(b)

[1 2 3 4 1 2 3 4 1 2 3 4]


In [3]:
b = [1, 2, 3]
a = np.array(b)
print(a*3, end = "")
a = np.array(b*3)
print(a)

[3 6 9][1 2 3 1 2 3 1 2 3]


## np.ones()

In [11]:
b = np.ones(3, dtype=int)
b

array([1, 1, 1])

In [68]:
b = np.ones((4,3), dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## np.zeros()

In [12]:
b = np.zeros(5,dtype=float)
b

array([0., 0., 0., 0., 0.])

In [17]:
b = np.zeros((3,4),dtype=float)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.full((m,n),fill_value)

In [20]:
b = np.full(3,5,dtype=float)
b

array([5., 5., 5.])

In [21]:
b = np.full((2,3),5,dtype=int)
b

array([[5, 5, 5],
       [5, 5, 5]])

In [27]:
a = np.empty(4, dtype = int)
print(a)

[ -496438309 -2119265506  1458263770   263195802]


## np.arange(start,stop,step)

In [28]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

## np.linespace(start,stop,sample_space)
* This will create by default 50 different sample within the given range both inclusive
* We can give sample value how much we want to generate
* start and stop values are inclusive

In [35]:
a = np.linspace(2,10)

print(a[3]-a[2])
print(a[16]-a[15])
print(a)

0.16326530612244916
0.16326530612244916
[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]


In [36]:
a = np.linspace(2,20,7,dtype=int)
print(a)

[ 2  5  8 11 14 17 20]


### endpoint=False, this will exclude the stop value

In [37]:
a = np.linspace(2,20,7,dtype=int,endpoint=False)
print(a)

[ 2  4  7  9 12 14 17]


# np.identity()
* we can only get m x m matrix only

# np.eye()
* we can get m x n matrix

In [38]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# np.random.rand()

In [63]:
np.random.rand()

0.11195406034210009

In [43]:
a = np.random.rand(3)
a

array([0.72840916, 0.60349426, 0.52132659])

In [45]:
a = np.random.rand(3,5)
a

array([[0.20673815, 0.88331483, 0.02414019, 0.80171393, 0.51523328],
       [0.08863969, 0.77012943, 0.33374868, 0.83835172, 0.97351671],
       [0.219075  , 0.86119677, 0.45724783, 0.68782793, 0.17889275]])

In [48]:
a = np.random.rand(2,4)*10
a

array([[3.59117901, 4.35094455, 6.14109765, 9.56877676],
       [0.12066501, 2.71331526, 6.81805379, 9.005185  ]])

# np.random.randint(low,high,size,dtype)
* high value is exclusive

In [58]:
a = np.random.randint(2,10,6)
a

array([2, 4, 9, 8, 5, 9])

In [59]:
a = np.random.randint(2,10,(2,6))
a

array([[8, 8, 6, 7, 2, 5],
       [7, 4, 4, 3, 5, 6]])

In [67]:
a = np.random.randint(10,size=(4,4))
a

array([[7, 3, 3, 2],
       [8, 6, 7, 9],
       [3, 4, 4, 8],
       [0, 5, 4, 3]])