# Boolean Indexing 1-D

In [1]:
import numpy as np

In [2]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 9  5 18 10 18 19  9 15]


In [3]:
print(b > 10)

[False False  True False  True  True False  True]


In [4]:
bool_arr = b > 10
print(bool_arr)

new_arr = b[bool_arr]
print(new_arr)

[False False  True False  True  True False  True]
[18 18 19 15]


In [5]:
new_arr = b[b>10]
print(new_arr)

[18 18 19 15]


In [6]:
new_arr = b[(b>10) & (b<18)]
print(new_arr)

[15]


In [7]:
print(b)
c = b
c

[ 9  5 18 10 18 19  9 15]


array([ 9,  5, 18, 10, 18, 19,  9, 15])

In [8]:
c[:3] = 19
print(c)
print(b)

[19 19 19 10 18 19  9 15]
[19 19 19 10 18 19  9 15]


In [9]:
c[c>15] = 100
print(c)
print(b)

[100 100 100  10 100 100   9  15]
[100 100 100  10 100 100   9  15]


In [10]:
print(b[b==100])

[100 100 100 100 100]


In [11]:
indexes = np.where(b==100)
print(indexes)
print(type(indexes))

(array([0, 1, 2, 4, 5], dtype=int64),)
<class 'tuple'>


In [12]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100  10 100 100   9  15]


In [13]:
indexes = np.where(b==100)
print(a[indexes])

['t' 'b' 'r' 'e' 'f']


# Boolean Indexing 2-D
* Boolean array should be of same shape as of our main array on which we will apply our boolean array to extract the data

In [14]:
import numpy as np

In [15]:
a = np.random.randint(1,30,(5,6),dtype=int)
a

array([[15,  9, 27, 10, 28, 17],
       [14, 16,  9, 24, 20, 24],
       [24, 10,  8, 27, 11,  6],
       [ 3, 11, 25, 21,  4, 16],
       [ 6, 25, 29,  8, 24, 26]])

In [16]:
bool_arr = a>20
bool_arr

array([[False, False,  True, False,  True, False],
       [False, False, False,  True, False,  True],
       [ True, False, False,  True, False, False],
       [False, False,  True,  True, False, False],
       [False,  True,  True, False,  True,  True]])

In [17]:
ans = a[bool_arr]
ans

array([27, 28, 24, 24, 24, 27, 25, 21, 25, 29, 24, 26])

In [18]:
b = a
print(a)

[[15  9 27 10 28 17]
 [14 16  9 24 20 24]
 [24 10  8 27 11  6]
 [ 3 11 25 21  4 16]
 [ 6 25 29  8 24 26]]


In [19]:
b[bool_arr] = 100
print(b)

[[ 15   9 100  10 100  17]
 [ 14  16   9 100  20 100]
 [100  10   8 100  11   6]
 [  3  11 100 100   4  16]
 [  6 100 100   8 100 100]]


In [20]:
c = np.random.randint(1,10,(2,2),dtype=int)
c # 2x2

array([[6, 2],
       [6, 6]])

In [21]:
c_bool = np.array([[True,False],[False,True],[True,True]])
c_bool # 3x2

array([[ True, False],
       [False,  True],
       [ True,  True]])

In [22]:
print(c[c_bool])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [23]:
print(b)

[[ 15   9 100  10 100  17]
 [ 14  16   9 100  20 100]
 [100  10   8 100  11   6]
 [  3  11 100 100   4  16]
 [  6 100 100   8 100 100]]


In [24]:
# We are updating column index 3 which are having value as 100 to 99
bool_arr = b[:,3] == 100
print(bool_arr)

[False  True  True  True False]


In [25]:
# b[boolean array,column index which you want to update]
# boolean array will tell where ever it is True select those rows (as in our case row 0 and 2 was having True value)
# then 3 will tell we need only column index 3 to be updated
b[bool_arr,3] = 99 
print(b)

[[ 15   9 100  10 100  17]
 [ 14  16   9  99  20 100]
 [100  10   8  99  11   6]
 [  3  11 100  99   4  16]
 [  6 100 100   8 100 100]]
