# Mathematical Operations

In [1]:
import numpy as np

In [2]:
li = [1,2,3,4,5]

a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[12 17 16  9 16]
[10 16 12 18  5]


In [3]:
li = [
    i+1
    for i in li
]
li

[2, 3, 4, 5, 6]

In [4]:
a = a+1
a

array([13, 18, 17, 10, 17])

In [5]:
c = a+b
c

array([23, 34, 29, 28, 22])

In [6]:
d = a-b
d

array([ 3,  2,  5, -8, 12])

In [7]:
e = a*b
e

array([130, 288, 204, 180,  85])

In [8]:
f = a/b
f

array([1.3       , 1.125     , 1.41666667, 0.55555556, 3.4       ])

In [9]:
g = a//b
g

array([1, 1, 1, 0, 3])

In [10]:
h = a**b
h

array([  419538377,  1048641536,  1333592769, -1486618624,     1419857])

In [13]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin()) # Index of minimum value
print(a.max())
print(a.argmax()) # Index of maximum value

[13 18 17 10 17]
75
15.0
10
3
18
1


In [14]:
print(a)
print(b)
print(a>b)

[13 18 17 10 17]
[10 16 12 18  5]
[ True  True  True False  True]


In [15]:
print(a==b)

[False False False False False]


In [16]:
print(a<b)

[False False False  True False]


In [17]:
print(a)
print(b)
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))

[13 18 17 10 17]
[10 16 12 18  5]
[ True  True  True  True  True]
[ True  True  True  True  True]
[0 0 0 0 0]


In [18]:
a[2] = 0
print(np.logical_not(a,b))

[0 0 1 0 0]


# Numpy Broadcasting
* If shape of the numpy array is different then how operations will be performed over the array
* Rules:
    * Dimensions are equal (Ex=>  x: 3x2 and y: 3x2)
    * One of the array is shape is 1 (Ex=> x: 3x3 and y: 3 or say 1x3) (This will add 2 extra row to array 'y' logically but we wont be able to see it)

In [2]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))

print(x)
print(y)

[[3 9 2]
 [6 7 5]
 [5 3 7]]
[[5 8 5]
 [2 8 6]
 [4 7 3]]


In [3]:
ans = x-y
print(ans)

[[-2  1 -3]
 [ 4 -1 -1]
 [ 1 -4  4]]


In [4]:
ans = x+y
print(ans)

[[ 8 17  7]
 [ 8 15 11]
 [ 9 10 10]]


In [5]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,3)

print(x)
print(y)

[[3 2 7]
 [3 1 6]
 [9 7 2]]
[5 1 3]


In [6]:
ans = x-y
print(ans)

[[-2  1  4]
 [-2  0  3]
 [ 4  6 -1]]


In [7]:
ans = y-x
print(ans)

[[ 2 -1 -4]
 [ 2  0 -3]
 [-4 -6  1]]


In [8]:
ans = x+y
print(ans)

[[ 8  3 10]
 [ 8  2  9]
 [14  8  5]]


In [9]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))

print(x)
print(y)

[[3 2]
 [3 9]
 [4 6]]
[[1 8 3]
 [4 2 5]]


In [10]:
ans = x-y
print(ans)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

### To make it compatible we will transpose one of the array

In [11]:
y = np.transpose(y)
ans = x-y
print(ans)

[[ 2 -2]
 [-5  7]
 [ 1  1]]


## resize()
## reshape()
The difference between them is that the reshape() does not change the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array 

In [12]:
x = np.random.randint(1,10,(3,2))
x

array([[8, 8],
       [3, 4],
       [9, 8]])

In [15]:
x.reshape(2,3)

array([[8, 8, 3],
       [4, 9, 8]])

In [16]:
x

array([[8, 8],
       [3, 4],
       [9, 8]])

In [17]:
x.resize(2,3)

In [18]:
x

array([[8, 8, 3],
       [4, 9, 8]])

# Examples - Terrorist Dataset

In [1]:
import numpy as np
import csv

In [ ]:
with open() as obj:
    data = csv.DictReader(obj,skipinitialspace=True)

    
killed = []
wounded = []
country = []
for i in data:
    killed.append(i['Killed'])
    country.append(i['Country'])
    wounded.append(i['Wounded'])
    
np_killed = np.array(killed) # we have to deal with empty values
np_wounded = np.array(wounded) # we have to deal with empty values

# will convert missing values to string 0.0 and then convert them to float then will convert them to int
np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded==''] = '0.0'

np_killed = np.array(np_killed,dtype=float)
np_wounded = np.array(np_wounded,dtype=float)

killed_wounded = np_killed+np_wounded
print(killed_wounded)
print(np.sum(killed_wounded))

In [ ]:
with open() as obj:
    data = csv.DictReader(obj,skipinitialspace=True)

    
killed = []
wounded = []
country = []
for i in data:
    killed.append(i['Killed'])
    country.append(i['Country'])
    wounded.append(i['Wounded'])
    
np_killed = np.array(killed) 
np_wounded = np.array(wounded) 

np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded==''] = '0.0'

np_killed = np.array(np_killed,dtype=float)
np_wounded = np.array(np_wounded,dtype=float)

killed_wounded = np_killed+np_wounded

# To print only those killed_wounded whose country is India
np_country = np.array(country)

bool_arr = np_country=='India'
ans = killed_wounded[bool_arr]
print(ans)
print(np.sum(ans))